POST http://localhost:3000/api/patients
Content-Type: application/json

{
    "name":"Martin Riggs3",
    "dateOfBirth":"1979-01-30",
    "ssn": "test",
    "gender":"male",
    "occupation":"Cop",
    "entries": [{
        "type": "OccupationalHealthcare",
        "id": "b4f4eca1-2aa7-4b13-9a18-4a5535c3c8da",
        "date": "2019-10-20",
        "specialist": "MD House",
        "description": "Yearly control visit. Cholesterol levels back to normal.",
        "employerName": "yritys 1",
        "discharge": {
          "date": "2019-08-05",
          "criteria": "test"
        },
        "diagnosisCodes": ["Z57.1", "Z74.3", "M51.2"]
    }]
    
}